version: '3'

services:
  database:
    platform: linux/x86_64
    image: mysql
    ports:
      - "3306:3306"
    container_name: vinylish_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vinylish
  adminer:
    image: adminer
    ports:
      - "9090:8080"